AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'lib/eet_cz/akami_patch.rb'
Metrics/LineLength:
 Max: 120
Documentation:
 Enabled: false
Style/ClassAndModuleCamelCase:
 Enabled: false
